services:
  php-simple-app2:
    build:
      context: .
      dockerfile: Dockerfile
    image: miguel1212/php-simple-app2:dev
    container_name: php-simple-app2
    ports:
      - "8082:80"
    volumes:
      - ./php-simple-app/src:/var/www/html
    restart: unless-stopped
