services:
  php-simple-app2:
    build:
      context: .
      dockerfile: Dockerfile
    image: miguel1212/php-simple-app2:dev
    container_name: php-simple-app2
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    # ðŸ‘‡ Monta la misma ruta anidada para ver cambios al instante
    volumes:
      - ./php-simple-app/src:/var/www/html
    restart: unless-stopped
